
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebApplication1.Database
{

using System;
    using System.Collections.Generic;
    
public partial class Employee
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Employee()
    {

        this.Insurence = new HashSet<Insurence>();

        this.User = new HashSet<User>();

    }


    public System.Guid EmployeeId { get; set; }

    public Nullable<double> Salary { get; set; }

    public Nullable<System.Guid> CompanyId { get; set; }

    public Nullable<System.Guid> InsuranceId { get; set; }

    public Nullable<System.Guid> ScheduleId { get; set; }



    public virtual Company Company { get; set; }

    public virtual Schedule Schedule { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Insurence> Insurence { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<User> User { get; set; }

}

}
