
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebApplication1.Database
{

using System;
    using System.Collections.Generic;
    
public partial class Forum
{

    public int ForumId { get; set; }

    public string ForumName { get; set; }

    public Nullable<int> CourseId { get; set; }

    public Nullable<System.Guid> CompanyId { get; set; }

    public Nullable<System.DateTime> CreateDate { get; set; }



    public virtual Company Company { get; set; }

    public virtual Course Course { get; set; }

}

}
