
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebApplication1.Database
{

using System;
    using System.Collections.Generic;
    
public partial class ForumEntries
{

    public int ForumId { get; set; }

    public int MessageId { get; set; }

    public string EntryContent { get; set; }

    public System.Guid UserId { get; set; }

    public Nullable<System.DateTime> CreateDate { get; set; }



    public virtual User User { get; set; }

}

}
