
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebApplication1.Database
{

using System;
    using System.Collections.Generic;
    
public partial class Insurence
{

    public System.Guid InsuranceID { get; set; }

    public string InsuranceType { get; set; }

    public string Status { get; set; }

    public System.DateTime StartDate { get; set; }

    public Nullable<System.Guid> EmployeeId { get; set; }

    public Nullable<System.Guid> RetireeId { get; set; }



    public virtual Employee Employee { get; set; }

    public virtual Retiree Retiree { get; set; }

}

}
