
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebApplication1.Database
{

using System;
    using System.Collections.Generic;
    
public partial class Message
{

    public System.Guid senderid { get; set; }

    public System.Guid recieverid { get; set; }

    public int messageid { get; set; }

    public string message1 { get; set; }

    public System.DateTime CreateDate { get; set; }



    public virtual User User { get; set; }

    public virtual User User1 { get; set; }

}

}
