
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebApplication1.Database
{

using System;
    using System.Collections.Generic;
    
public partial class Resource
{

    public string ResourceName { get; set; }

    public string ResourceURL { get; set; }

    public int ResourceId { get; set; }

    public System.Guid CompanyId { get; set; }

    public int CourseId { get; set; }



    public virtual Company Company { get; set; }

    public virtual Course Course { get; set; }

}

}
