
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebApplication1.Database
{

using System;
    using System.Collections.Generic;
    
public partial class Schedule
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Schedule()
    {

        this.Employee = new HashSet<Employee>();

    }


    public System.Guid ScheduleID { get; set; }

    public Nullable<System.Guid> EmployeeId { get; set; }

    public System.DateTime Date { get; set; }

    public string DateNote { get; set; }

    public Nullable<System.Guid> StudentId { get; set; }

    public Nullable<System.Guid> UserId { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Employee> Employee { get; set; }

    public virtual Student Student { get; set; }

    public virtual User User { get; set; }

}

}
