
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebApplication1.Database
{

using System;
    using System.Collections.Generic;
    
public partial class Transcript
{

    public int cid { get; set; }

    public System.Guid StudentID { get; set; }

    public string LetterGrade { get; set; }

    public string CourseName { get; set; }

    public Nullable<double> GPA { get; set; }

    public string Semester { get; set; }

    public Nullable<int> Attendance { get; set; }

    public int tid { get; set; }



    public virtual Course Course { get; set; }

    public virtual Student Student { get; set; }

}

}
