
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebApplication1.Database
{

using System;
    using System.Collections.Generic;
    
public partial class User
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public User()
    {

        this.ForumEntries = new HashSet<ForumEntries>();

        this.Message = new HashSet<Message>();

        this.Message1 = new HashSet<Message>();

        this.Schedule = new HashSet<Schedule>();

        this.Vacation = new HashSet<Vacation>();

    }


    public System.Guid UserID { get; set; }

    public string FullName { get; set; }

    public string Mail { get; set; }

    public string Adress { get; set; }

    public string PhoneNumber { get; set; }

    public Nullable<System.Guid> StudentID { get; set; }

    public Nullable<System.Guid> EmployeeID { get; set; }

    public int UserType { get; set; }

    public Nullable<System.Guid> TeacherId { get; set; }

    public Nullable<System.Guid> ManagerId { get; set; }

    public string Username { get; set; }

    public string Password { get; set; }

    public string CV { get; set; }



    public virtual Employee Employee { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ForumEntries> ForumEntries { get; set; }

    public virtual Manager Manager { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Message> Message { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Message> Message1 { get; set; }

    public virtual Student Student { get; set; }

    public virtual Teacher Teacher { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Schedule> Schedule { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Vacation> Vacation { get; set; }

}

}
