
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebApplication1.Database
{

using System;
    using System.Collections.Generic;
    
public partial class Vacation
{

    public int vid { get; set; }

    public int VacationType { get; set; }

    public System.DateTime VacationDate { get; set; }

    public System.Guid UserId { get; set; }



    public virtual User User { get; set; }

}

}
