/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package academicwarfare.assets.menuframes;
import javax.swing.*;

/**
 *
 * @author onur.elbirlik
 */
public class LoadGame extends javax.swing.JPanel {

    /**
     * Creates new form LoadGame
     */
    public LoadGame(JFrame frame) {
        initComponents();
        this.mainFrame = frame;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        saveNo1 = new javax.swing.JButton();
        saveNo2 = new javax.swing.JButton();
        saveNo3 = new javax.swing.JButton();
        loadGameText = new javax.swing.JLabel();
        mainMenuButton = new javax.swing.JButton();

        saveNo1.setText("Save 1");
        saveNo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveNo1ActionPerformed(evt);
            }
        });

        saveNo2.setText("Save 2");
        saveNo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveNo2ActionPerformed(evt);
            }
        });

        saveNo3.setText("Save 3");
        saveNo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveNo3ActionPerformed(evt);
            }
        });

        loadGameText.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        loadGameText.setText("    Load Game");

        mainMenuButton.setText("Return Back To Main Menu");
        mainMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainMenuButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(mainMenuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(198, 198, 198)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(saveNo1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(saveNo3, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(saveNo2, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(loadGameText, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(217, 217, 217))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(loadGameText)
                .addGap(50, 50, 50)
                .addComponent(saveNo1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(saveNo2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(saveNo3)
                .addGap(55, 55, 55)
                .addComponent(mainMenuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(99, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void saveNo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveNo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saveNo1ActionPerformed

    private void saveNo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveNo2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saveNo2ActionPerformed

    private void saveNo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveNo3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saveNo3ActionPerformed

    private void mainMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainMenuButtonActionPerformed
        // TODO add your handling code here:
        
        mainFrame.remove( this );
        mainFrame.add( new MainMenu(mainFrame));
        
        
        mainFrame.pack();
        mainFrame.repaint();
    }//GEN-LAST:event_mainMenuButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel loadGameText;
    private javax.swing.JButton mainMenuButton;
    private javax.swing.JButton saveNo1;
    private javax.swing.JButton saveNo2;
    private javax.swing.JButton saveNo3;
    private JFrame mainFrame ;
    // End of variables declaration//GEN-END:variables
}
